version: 2

models:
  - name: french
    description: "test french table"
    columns:
      - name: FR
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
          - accepted_values:
              values:  ['un', 'deux', 'troi']

  - name: enfr
    description: "insure all values in en column are also in ende"
    columns:
      - name: EN
        data_tests:
          - relationships:
              to: ref('ende')
              field: EN
