
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: french
    description: "test french table"
    columns:
      - name: FR
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
          - accepted_values:
              values: ['un', 'deux']

  - name: enfr
    description: "insure all values in en column are also in ende"
    columns:
      - name: EN
        data_tests:
          - relationships:
              to: ref('ende')
              field: EN
